### ISSUE TITLE
bower.json issues?

### ISSUE THREAD

**Issue by MikeiLL** [robinpoort/vanilla-js-responsive-menu#10]
Hi and thanks for the nice work, man.

I'm unable to get the files to load with bower. On apollo.js I was able to get the file to load by adding:

```
  "main": [
    "dist/apollo.min.js"
  ],
```

to the bower.json file, but the only way I can seem to get this to work is adding the files manually.

This is the bower.json file _after_ adding a link to the js file:

```
{
  "name": "vanilla-js-responsive-menu",
  "description": "Vanilla JS responsive and accessible menu",
  "main": [
    "scss/responsivemenu.scss",
    "vanilla.js.responsive.menu.js"
  ],
  "dependencies": {
    "apollo.js": "~1.7.0"
  },
  "keywords": [
    "Responsive",
    "Menu",
    "Navigation",
    "Accessible",
    "vanilla JS"
  ],
  "authors": [
    "Robin Poort "
  ],
  "license": "MIT",
  "ignore": [
    "demo"
  ]
}
```

But still not getting added to my main.css and main.js files. Can't seem to determine why.

bower_components dir structure:

```
└── vanilla-js-responsive-menu
    ├── LICENSE
    ├── README.md
    ├── bower.json
    ├── css
    │   ├── demo.css
    │   ├── demo.css.map
    │   ├── responsivemenu.css
    │   └── responsivemenu.css.map
    ├── scss
    │   ├── demo.scss
    │   └── responsivemenu.scss
    └── vanilla.js.responsive.menu.js
```

**Comment by robinpoort** [comment]
Hi @MikeiLL 

Thanks for the compliment and sorry for this late reply. For some reason I didn't get any notifications and I was on holiday as well. Something went terribly wrong!

Do you still have the problem?

For my website projects I'm running [Grunt](http://gruntjs.com/) and I'm compiling my **CSS** and **JS** files from the `bower_components` folder. So for example I create my JS files like this (using Grunt):

``` js
uglify: {
    options: {
        soureMap: true
    },
    build: {
        files: {
            'js/scripts.js': [
                'bower_components/apollo.js/dist/apollo.min.js',
                'bower_components/vanilla-js-responsive-menu/vanilla.js.responsive.menu.js',
                'scripts/main.js'
            ]
        }
    }
}
```

The SCSS files I usually create like this:

``` scss
// Variables
@import "utilities/variables";

// Mixins
@import "utilities/mixins";

// Vendor
@import "../../../../bower_components/vanilla-js-responsive-menu/scss/responsivemenu";
```

Then in the `variables` file I can overwrite the menu settings like so:

``` scss
// Responsive menu
$vjsm-multi-level:      false;
```

As long as you load your own variables before the responsive menu `@import` the variables in the `@import` will be overwritten.

Then in Grunt I just run:

``` js

// Compile sass files
sass: {
    dist: {
        files: {
            'css/style.css': ['scss/style.scss'],
        }
    }
}
```

Does this help? Or did I get you totally wrong? :)

**Comment by robinpoort** [comment]
Closing because of no reaction for 2 months

**Comment by MikeiLL** [comment]
Oh hey, man. For some reason I didn't get notification either. I use `gulp` and not `grunt` for my workflow.
When I add most bower packages, like `bootstrap_bower` for example, because of the structure of it's bower.json file, the files automatically get pulled into the compiled `dist` directory. Am using the [roots/sage](https://github.com/roots/sage) wordpress starter theme. Still having an issue with this. Just hadn't noticed yet. And not sure of the correct solution, but I think the bower.json file could possibly be modified to make it work as I had expected.

**Comment by robinpoort** [comment]
Could you maybe remove the vanilla-js-responsive-menu folder and run `bower install vanilla-js-responsive-menu --save-dev`. What does that give you?
