### ISSUE TITLE
Displaying the menu without using togglebutton

### ISSUE THREAD

**Issue by falconerie** [robinpoort/vanilla-js-responsive-menu#12]
Hi, how can I make this work without using the togglebutton in mobile. Just display the menu right away?

**Comment by robinpoort** [comment]
Hi @designhash,

Thanks for using/considering this software! But if you've got no need for a toggle button then there's no need to use this plugin. You can just use plain CSS to make your menu look different on mobile screens rather then using JavaScript do this for you.
