### ISSUE TITLE
Plus button floating non-evenly

### ISSUE THREAD

**Issue by sashabeep** [robinpoort/vanilla-js-responsive-menu#19]
<img width="384" alt="Снимок экрана 2021-02-12 в 02 25 19" src="https://user-images.githubusercontent.com/5689796/107712138-ecb63800-6cd9-11eb-9dd6-34a42ce12b3e.png">

FF latest.
Maybe some clearing needed for parent? Tried ```clear:botn``` on the **.rm-parent** selector on the small screen - works

<img width="456" alt="Снимок экрана 2021-02-12 в 02 31 39" src="https://user-images.githubusercontent.com/5689796/107712441-7960f600-6cda-11eb-8d8d-0612531bcf85.png">

**Comment by robinpoort** [comment]
@sashabeep Thanks for the suggestion! The demo is updated accordingly. Note that this is just the demo, if you want to add this to your own menu's you'll still have to add the according CSS to your own website(s).
