### ISSUE TITLE
Touchscreen support for large screens

### ISSUE THREAD

**Issue by sashabeep** [robinpoort/vanilla-js-responsive-menu#20]
When the menu is expanded to full width if screen width is enough (for example, ipad), parent items click does not open the submenu

**Comment by robinpoort** [comment]
@sashabeep Have you tried this on an actual iPad or on a browser using a device toolbar? At least in iOs I know that the submenu will in fact display on click, and on a second click you will visit the parent link. However this does not work on Chrome using the devices tab for example. You need a good emulator or an actual device to see this in action.

**Comment by sashabeep** [comment]
@robinpoort will try to try in some next day
