### ISSUE TITLE
too late for dropdown

### ISSUE THREAD

**Issue by hans2103** [robinpoort/vanilla-js-responsive-menu#4]
When on an iPad I'm not able to click on a submenu item when the parent menu item contains a links
The iPad is big enough not to collapse to mobile menu. 

```
<ul>
  <li>
    <a href="link">parent</a>
    <ul>
      <li><a href="sublink">submenu</a></li>
    </ul>
  </li>
</ul>
```

I would like to be able to open the dropdown on a single click. And open the link of the parent on a double click.

**Comment by robinpoort** [comment]
@hans2103 Added support, just update the menu to the latest version. Let me know if this fixes it for you as well.

**Comment by hans2103** [comment]
Hard time testing the fix since it also has some CSS changes affecting the height of the menu on tablet view. See screenshot

<img width="941" alt="schermafdruk 2016-03-15 23 48 33" src="https://cloud.githubusercontent.com/assets/639822/13796703/7c193406-eb08-11e5-9779-26f707b7c6c4.png">

**Comment by robinpoort** [comment]
@hans2103 I forgot to mention that there's a new SCSS setting that you should enable.

Set `$vjsm-multi-level` to `true` to enable the CSS to make it work.

**Comment by hans2103** [comment]
@robinpoort 
I've set `$vjsm-multi-level` to `true` to enable the CSS to make it work.
Now I have another issue to solve... see screencapture below. 

![m2-cachemanagement-selectalls](https://cloud.githubusercontent.com/assets/639822/13821943/0f16cf20-eba4-11e5-8f62-76b937ea0828.gif)

**Comment by robinpoort** [comment]
@hans2103 You have fixed this right? If so can you close the issue?

**Comment by hans2103** [comment]
issue is solved... therefor issue can be closed.
